# Form implementation generated from reading ui file 'record_data_widget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_record_data_widget(object):
    def setupUi(self, record_data_widget):
        record_data_widget.setObjectName("record_data_widget")
        record_data_widget.resize(756, 569)
        self.gridLayout = QtWidgets.QGridLayout(record_data_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.start_record_button = QtWidgets.QPushButton(record_data_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_record_button.sizePolicy().hasHeightForWidth())
        self.start_record_button.setSizePolicy(sizePolicy)
        self.start_record_button.setObjectName("start_record_button")
        self.gridLayout.addWidget(self.start_record_button, 1, 0, 1, 1)
        self.fps_record_spin_box = QtWidgets.QSpinBox(record_data_widget)
        self.fps_record_spin_box.setMinimum(15)
        self.fps_record_spin_box.setMaximum(10000)
        self.fps_record_spin_box.setObjectName("fps_record_spin_box")
        self.gridLayout.addWidget(self.fps_record_spin_box, 1, 2, 1, 1)
        self.fps_record_label = QtWidgets.QLabel(record_data_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fps_record_label.sizePolicy().hasHeightForWidth())
        self.fps_record_label.setSizePolicy(sizePolicy)
        self.fps_record_label.setWordWrap(True)
        self.fps_record_label.setObjectName("fps_record_label")
        self.gridLayout.addWidget(self.fps_record_label, 1, 1, 1, 1)
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setObjectName("main_layout")
        self.gridLayout.addLayout(self.main_layout, 0, 0, 1, 3)
        self.path_to_frames_line_edit = QtWidgets.QLineEdit(record_data_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.path_to_frames_line_edit.sizePolicy().hasHeightForWidth())
        self.path_to_frames_line_edit.setSizePolicy(sizePolicy)
        self.path_to_frames_line_edit.setReadOnly(True)
        self.path_to_frames_line_edit.setObjectName("path_to_frames_line_edit")
        self.gridLayout.addWidget(self.path_to_frames_line_edit, 2, 2, 1, 1)
        self.open_dialog_button = QtWidgets.QPushButton(record_data_widget)
        self.open_dialog_button.setObjectName("open_dialog_button")
        self.gridLayout.addWidget(self.open_dialog_button, 2, 0, 1, 1)
        self.path_to_frames_label = QtWidgets.QLabel(record_data_widget)
        self.path_to_frames_label.setObjectName("path_to_frames_label")
        self.gridLayout.addWidget(self.path_to_frames_label, 2, 1, 1, 1)

        self.retranslateUi(record_data_widget)
        QtCore.QMetaObject.connectSlotsByName(record_data_widget)

    def retranslateUi(self, record_data_widget):
        _translate = QtCore.QCoreApplication.translate
        record_data_widget.setWindowTitle(_translate("record_data_widget", "Form"))
        self.start_record_button.setText(_translate("record_data_widget", "Start"))
        self.fps_record_label.setText(_translate("record_data_widget", "<span>FPS to record:</span><br>\n"
"<span> Minimum: 15, Maximum: 10000 </span>"))
        self.open_dialog_button.setText(_translate("record_data_widget", "Open Dialog"))
        self.path_to_frames_label.setText(_translate("record_data_widget", "Selected path to the recorded frames:"))
